name: CI

on:
  push:
    branches:
      - main
      - '[0-9].[0-9]+'  # matches to backport branches, e.g. 3.6
    tags: [ 'v*' ]
    paths-ignore: [ "docs/**" ]
  pull_request:
    branches:
      - main
      - '[0-9].[0-9]+'
      - 'update/pre-commit-autoupdate'
    paths-ignore: [ "docs/**" ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Setup Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Run pre-commit
      uses: pre-commit/action@v2.0.3

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: testorm
          POSTGRES_USER: testorm
          POSTGRES_PASSWORD: testorm

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Setup Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        cache: pip
        cache-dependency-path: |
          requirements/base.txt
          requirements/local.txt
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install -r requirements/local.txt
    - name: Test
      run: pytest tests/

